### ISSUE TITLE
Prison v2.2 Ranks Malfunctions

### ISSUE THREAD

**Issue by eepgaming** [SirFaizdat/Prison#170] opened 2016-07-19 15:42 UTC
In the new update, or since i uploaded it, all my ranks from like b to U are being missed, when you do /rankup from a, it takes you to W, and it does this with some others as well. Please help!

Also, when i do /ranks it says 'Internal error occurred'

Shows this in console: 
```
18.07 19:16:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:75) ~[?:?] 18.07 19:16:06 [Server] INFO Caused by: java.lang.NullPointerException 18.07 19:16:06 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_60] 18.07 19:16:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_60] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT52-1.9.jar:git-Spigot-2038f4a-44216f1] 18.07 19:16:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ranks' in plugin Prison v2.2.2 18.07 19:16:06 [Server] ERROR null
```

This issue is fixed on Versiob 2.1.6 and below.

**Comment by eepgaming** [comment] 2016-08-03 09:54
Is this issue fixed?

**Comment by eepgaming** [comment] 2016-08-26 23:26
??

**Comment by SirFaizdat** [comment] 2016-09-08 00:17
I am unable to reproduce or find other instances of this problem (I've been trying for a while). Please ensure your installation is valid, with your Spigot being at least 1.8 or greater, your ranks files not being corrupted, and your Vault, permissions, and economy plugins being up to date.

**Comment by eepgaming** [comment] 2016-09-09 16:36
Ok, thanks, I'll look into it.

**Comment by Robslayer** [comment] 2016-09-11 21:51
did u manage to fix this? i have this problem too

**Comment by eepgaming** [comment] 2016-09-11 22:19
I haven't been able to look into it yet, ill try tomorrow.

**Comment by Robslayer** [comment] 2016-09-13 15:25
i found out how to fix, you have to set the id's for each rank starting from 0 then it should be fine

**Comment by Camouflage100** [comment] 2016-10-02 20:38
Fixed in commit https://github.com/SirFaizdat/Prison/commit/c2ba3632226eb49e835c083f42fb1ebf5d8a1f02

**Closed by Camouflage100** 2016-10-02 20:38 UTC
Labels: bug, can't reproduce
