### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by DaWizzyG** [SirFaizdat/Prison#193] opened 2016-12-09 23:15 UTC
I have a few issues that I hope you can handle.
1. I have PEX (PermissionsEx) and the prefixes don't show when anyone ranks up.
2. When I rank up to "E" and then when I do /rankup it says "You've ranked up to D!", so I did /rankup again and it ranked me up to "E" and I did /rankup again which sent me back to D. It won't let me rankup past E

**Comment by DMP9-MC** [comment] 2016-12-21 21:39
You can use the [Prison Data Editor](http://go.dmp9software.co.uk) if you're on Windows to edit the rank files to give the rank files the following IDs:

A has ID 0
B has ID 1
C has ID 2
D has ID 3
E has ID 4
F has ID 5

Or use the in-game prison commands

/pranks set <rank> id <value>

Or better yet, I'll do it all for you. Zip up the rank files and attach the zip folder to a GitHub comment.

**Comment by DMP9-MC** [comment] 2016-12-21 21:41
Duplicate of #188

**Closed** 2016-12-30 16:14 UTC
