### ISSUE TITLE
Ranks / Ranking

### ISSUE THREAD

**Issue by eepgaming** [SirFaizdat/Prison#191] opened 2016-11-18 16:01 UTC
I have the latest version.

But when i do /rankup, it either goes from the default rank to '2' (I have ranks 1 and 2) or to '1', but when you /rankup again, it keeps saying you ranked up to 1.

Please help.

I'm posting this again because it got closed without it being fixed.

**Comment by Camouflage100** [comment] 2016-11-18 16:06
Duplicate of #188

**Comment by eepgaming** [comment] 2016-11-18 16:15
What are you doing, maybe fix it before you close it.

**Comment by Camouflage100** [comment] 2016-11-18 16:20
It's a duplicate issue, so the duplicate is closed and the original is kept open until it's fixed.

**Closed by Camouflage100** 2016-11-18 16:20 UTC

**Comment by eepgaming** [comment] 2016-11-18 16:22
When will it get fixed? ETA?

**Comment by Camouflage100** [comment] 2016-11-18 16:23
We've been focusing on Prison 3 mainly recently. I don't have an exact
estimate for a v2.3 release, if one comes out in time.

**Comment by eepgaming** [comment] 2016-11-18 16:35
Okay, thanks.
