### ISSUE TITLE
ranks issue

### ISSUE THREAD

**Issue by lcsmxd** [SirFaizdat/Prison#189] opened 2016-11-11 15:44 UTC
HELP !

I manage a server with my principal and alt accounts, alt is for see if plugins work. I have set up permissons for it but i've a problem !

1) When i type /rankup (with alt acc) instead saying You reached the highest rank. it puts me to rank A!

2) When i relog my rank resets !!! help

**Comment by Camouflage100** [comment] 2016-11-13 23:27
Duplicate of #188

**Closed by Camouflage100** 2016-11-13 23:27 UTC
