### ISSUE TITLE
Broken Ranks

### ISSUE THREAD

**Issue by ItsGJK** [SirFaizdat/Prison#151] opened 2016-06-11 18:49 UTC
I run a server called HungerMC, and I love using your Prison plugin. Recently, (finally) I realized that whenever someone ranked up, their PEX prefix would reset. Here's an example:

[A] Owner ItsGJK: hi
ItsGJK ranked up to B
[B] default ItsGJK: hi

(default rank is the pex default rank) 
Is there a way to fix this? I'm still in the Owner group, but it doesn't show the prefix.

**Comment by SirFaizdat** [comment] 2016-06-11 18:52
Duplicate of #150 

> PermissionsEx doesn't allow for more than one prefix on a player. You can solve this by having the staff prefixes as suffixes, and the Prison rank prefixes as prefixes. It also helps to have the staff ranks in a separate ladder, so Prison doesn't confuse them with the prison ranks.

**Comment by ItsGJK** [comment] 2016-06-11 19:22
That doesn't work. I'm in two groups: Owner and Arank
Arank has a suffix of A
Owner has a prefix of Owner
whenever I rankup, even though I'm out of the default group, my prefix gets reset to default (yet I'm still in Owner and Brank)

**Comment by ItsGJK** [comment] 2016-06-11 19:28
I don't see how this is a duplicate of ticket #150

**Comment by SirFaizdat** [comment] 2016-06-11 20:29
Sorry, I didn't understand your problem entirely. Brank may still have the default prefix. Try `/pex group Brank prefix ""`

**Comment by ItsGJK** [comment] 2016-06-11 20:33
It slightly worked. I put "" as the prefix and it autoset it to default, so I put a space in between " " and now everyone's prefix is just a blank space. I think Brank (and all the other ranks) are now overlapping Owner etc.

**Comment by SirFaizdat** [comment] 2016-06-11 20:33
Try putting the staff ranks in a separate rank ladder than the prison ranks.

**Comment by ItsGJK** [comment] 2016-06-11 20:34
How do I do that?

**Comment by SirFaizdat** [comment] 2016-06-11 20:40
`/pex grop <group> rank <level> <ladder name>`

* The level is a number. The higher the level, the higher up on the ladder the rank is.
* The ladder name can be anything, but mustn't include spaces.

Example:

`/pex group Owner rank 100 Staff`

**Comment by ItsGJK** [comment] 2016-06-11 20:45
Didn't work.

Owner is 100 rank in Staff
B is rank 2 in Ranks

It's still

[B] _(nothing)_ ItsGJK

the nothing is just a blank rank

**Comment by ItsGJK** [comment] 2016-06-11 21:30
Hello, sir?

**Comment by SirFaizdat** [comment] 2016-06-11 21:47
Can you send me your Prison folder and your permissions.yml file so that I can attempt to reproduce the problem?

**Comment by ItsGJK** [comment] 2016-06-11 21:49
Okay. One moment BTW, my ranks are roman numerals. For the sake of making it easy I made it A and B etc.

**Comment by ItsGJK** [comment] 2016-06-11 21:51
The first one is prison and second perms.
[net2ftp-1465681623.zip](https://github.com/SirFaizdat/Prison/files/310516/net2ftp-1465681623.zip)
[net2ftp-1465681660.zip](https://github.com/SirFaizdat/Prison/files/310517/net2ftp-1465681660.zip)

**Comment by SirFaizdat** [comment] 2016-06-11 21:52
I will be able to look at it either later tonight or tomorrow.

**Comment by ItsGJK** [comment] 2016-06-11 21:52
Okay, that's fine.

**Comment by ItsGJK** [comment] 2016-06-12 18:30
Sir? Have you found out how to fix it?

**Comment by ItsGJK** [comment] 2016-06-13 00:04
?

**Comment by ItsGJK** [comment] 2016-06-13 16:49
It's been two days now. Are you here?

**Comment by SirFaizdat** [comment] 2016-06-13 20:41
This will take a little while to debug, and since I currently have final exams at school, I am unable to look into it until either tomorrow or Wednesday. I'm really sorry :(

I did look at it yesterday when I had time, and I realized this is an issue with Prison's rankup system - something that can't be fixed in Prison 2 (which is why I'm making a Prison 3).

**Comment by ItsGJK** [comment] 2016-06-13 20:53
Thanks for responding! Okay, that's fine. I was so excited to be releasing my prison server to the public in a few days, all I needed was that done. Do you know when Prison 3 will come out?

**Comment by SirFaizdat** [comment] 2016-06-13 20:57
I'm trying not to announce any release dates, because it's a hefty project. It will be out sometime this year.

**Comment by ItsGJK** [comment] 2016-06-13 20:59
Is there any way around it? I'm trying to get my server out before I go to Hawaii in a couple of weeks. I like your plugin and don't want to switch, but I might have to get a different plugin if no way to solve it.

**Comment by SirFaizdat** [comment] 2016-06-13 21:00
There's a certain way to configure permissions so that they work properly in these situations. It takes a bit of time, so I'll try to do it by Wednesday.

**Comment by ItsGJK** [comment] 2016-06-13 21:05
Okay, thanks. Please keep me posted, and if it doesn't appear to be a way to fix it, don't hesitate to tell me.

**Comment by ItsGJK** [comment] 2016-06-16 16:42
Hey, any luck?

**Comment by SirFaizdat** [comment] 2016-06-16 16:44
I've been working on Prison v2.2, which should fix your problem. I'm finishing it up, it should be out today early tomorrow morning.

**Comment by ItsGJK** [comment] 2016-06-16 16:45
Thank you! I actually kinda found a hard way around it which could be setting user's prefix's, but hopefully this fixes it for good!

**Comment by SirFaizdat** [comment] 2016-06-16 17:02
The new update doesn't fix the issue after all (I thought it did). The issue is due to some of your ranks overriding other rank prefixes. For example, your prison ranks (I through Free) are setting the player's prefix to '  ', which is why no prefix is showing.

**Comment by ItsGJK** [comment] 2016-06-16 18:01
Is there a way to somehow disable the prefix in I through Free? (setting it to "" sets it to Guest)

**Comment by SirFaizdat** [comment] 2016-06-16 18:03
That would require you to recreate the permissions.yml file. If you give me a list of all the ranks on your server, I can do it for you (but you'll have to add the permissions again).

**Comment by ItsGJK** [comment] 2016-06-16 18:06
I think I'm fine then. I think I actually have found a solution that suits me with the user prefixes.

**Comment by SirFaizdat** [comment] 2016-06-16 18:07
Alright

**Comment by ItsGJK** [comment] 2016-06-16 18:07
Thanks for helping me! Good luck with the stuff.

**Closed by SirFaizdat** 2016-06-16 18:07 UTC
Labels: support
